# Values are documented at:
#  https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus/values.yaml

server:
  replicaCount: 1

  global:
    scrape_interval: 1m
    scrape_timeout: 15s
    evaluation_interval: 1m

  retention: "15d"
  retentionSize: ""

  persistentVolume:
    enabled: true
    accessModes:
      - ReadWriteOnce
    mountPath: /data
    subPath: ""
    size: 8Gi
    storageClassName: longhorn

  alertmanagers: []

  resources: {}

  dnsConfig:
    nameservers:
      - 10.10.10.10

  revisionHistoryLimit: 3

ruleFiles: {}

serverFiles:
  alerting_rules.yml: {}
  recording_rules.yml: {}
  prometheus.yml:
    scrape_configs:
      - job_name: node-sn3-ntp
        static_configs:
        - targets: ['10.70.90.138:9100']
      - job_name: nycmesh-1934-pve-mastodon
        static_configs:
        - targets: ['10.70.187.12:9100']
      - job_name: nycmesh-713-02-prem1
        static_configs:
        - targets: ['10.70.90.142:9100']
      - job_name: 'snmp mikrotik'
        scrape_interval: 30s
        scrape_timeout: 20s
        static_configs:
          - targets:
            - 10.42.43.18     # lhg60 SN1 - Henry (407)
            - 10.70.161.167   # lhg60 Rivington (2463) - Henry (407)
            - 10.70.188.63    # lhg60 Grand (1932) - Rivington (2463)
            - 10.101.40.247   # cube nycmesh-5283-60gx3 
            - 10.96.107.184   # nycmesh-430-cube60g
            - 10.69.73.125    # nycmesh-7325-cube60g
            - 10.96.54.218    # nycmesh-219-60xg3
            - 10.103.204.102  # nycmesh7985-cube60g
            - 10.96.107.185   # nycmesh-lhg60-430
            - 10.70.188.202   # nycmesh-1932-cubepro-1933
        metrics_path: /snmp
        params:
          module: [mikrotik]
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: snmpexporter-prometheus-snmp-exporter.snmpexporter.svc.cluster.local:9116  # The SNMP exporter's real hostname:port.

extraScrapeConfigs: ""

alertmanager:
  enabled: false

kube-state-metrics:
  enabled: false

prometheus-node-exporter:
  enabled: false

prometheus-pushgateway:
  enabled: false
