# Values are documented at:
#  https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml

replicas: 1

dnsConfig:
  nameservers:
    - 10.10.10.10

ingress:
  enabled: true
  ingressClassName: traefik
  path: /
  pathType: Prefix
  hosts:
    - grafana-dev.mesh.nycmesh.net

resources:
  requests:
    memory: 256Mi
    cpu: 100m
  limits:
    memory: 512Mi
    cpu: 200m

persistence:
  type: pvc
  enabled: true
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  size: 10Gi
  finalizers:
    - kubernetes.io/pvc-protection

adminUser: admin
# adminPassword: # Set via the github actions workflow

revisionHistoryLimit: 4
