replicas: 1

dnsConfig:
  nameservers:
    - 10.10.10.10

ingress:
  enabled: false
  ingressClassName: traefik
  path: /
  pathType: Prefix
  hosts:
    - grafana-new.mesh.nycmesh.net

resources: {}

persistence:
  type: pvc
  enabled: true
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  size: 10Gi
  finalizers:
    - kubernetes.io/pvc-protection

adminUser: admin
# adminPassword: # Set via the github actions workflow

revisionHistoryLimit: 4