name: Deploy Influxdb

on:
  push:
    branches:
      - main
  workflow_dispatch:
    branches:
      - main

permissions: read-all

jobs:
  deploy_to_dev3:
    name: Deploy to dev 3
    uses: ./.github/workflows/helm-deploy.yaml
    with:
      environment: dev3
    secrets: inherit
    if: github.ref == 'refs/heads/main'

  # deploy_to_prod1:
  #   name: Deploy to prod 1
  #   needs: deploy_to_dev3
  #   uses: ./.github/workflows/helm-deploy.yaml
  #   with:
  #     environment: prod1
  #   secrets: inherit
  #   if: github.ref == 'refs/heads/main'
